/**
 * examples/users-split/models/user.ts
 *
 * ORM model fixture representing the monolithic `users` table.
 * This is the entity that SchemaForge will analyse during AST scanning.
 *
 * Status: FIXTURE ONLY – not connected to a real ORM/database.
 * Represents the "before" state of the users-split migration.
 */

/**
 * Represents a row in the monolithic `users` table (pre-migration).
 *
 * ⚠️  After the migration this entity will be split into:
 *   - UserAccount  (id, email, passwordHash, createdAt)
 *   - UserProfile  (userId, displayName, avatarUrl, bio, updatedAt)
 */
export interface User {
  id: string;
  // auth fields → will move to UserAccount
  email: string;
  passwordHash: string;
  createdAt: Date;
  // profile fields → will move to UserProfile
  displayName: string | null;
  avatarUrl: string | null;
  bio: string | null;
  updatedAt: Date;
}

// Placeholder: the concrete ORM class will be generated by the Code Refactor stage.
// export class UserEntity implements User { ... }  // TODO: not yet implemented
