-- examples/users-split/schema.sql
--
-- Deterministic fixture: the monolithic `users` table that SchemaForge
-- will later split into `user_accounts` and `user_profiles`.
--
-- Status: FIXTURE ONLY – not connected to a real database in this version.
-- The full migration DDL will be generated by the Migration Plan stage.

-- ── Source: Monolithic table (before migration) ──────────────────────────────

CREATE TABLE users (
  id            UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
  -- auth / identity
  email         VARCHAR(255)    NOT NULL UNIQUE,
  password_hash VARCHAR(255)    NOT NULL,
  created_at    TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
  -- profile data
  display_name  VARCHAR(100),
  avatar_url    TEXT,
  bio           TEXT,
  updated_at    TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_users_email ON users (email);


-- ── Target: Split tables (after migration – NOT YET GENERATED) ──────────────

-- user_accounts: authentication / identity data
-- CREATE TABLE user_accounts ( ... );   -- TODO: generated by MigrationPlan

-- user_profiles: display / profile data
-- CREATE TABLE user_profiles ( ... );   -- TODO: generated by MigrationPlan
