/**
 * examples/users-split/dao/user-dao.ts
 *
 * DAO fixture for the monolithic `users` table (pre-migration).
 * Demonstrates the raw SQL queries that SchemaForge's AST analyser
 * will detect and flag as requiring updates after the table split.
 *
 * Status: FIXTURE ONLY – no real database connection.
 * The refactored DAO (targeting user_accounts + user_profiles) will be
 * generated by the Code Refactor stage.
 */

import type { User } from "../models/user";

/**
 * IUserDAO – interface that the AST analyser will discover.
 * After migration this will be split into IUserAccountDAO + IUserProfileDAO.
 *
 * ⚠️  NOT YET IMPLEMENTED – concrete implementation pending DB connection.
 */
export interface IUserDAO {
  findById(id: string): Promise<User | null>;
  findByEmail(email: string): Promise<User | null>;
  create(user: Omit<User, "id" | "createdAt" | "updatedAt">): Promise<User>;
  update(id: string, patch: Partial<User>): Promise<User | null>;
  deleteById(id: string): Promise<boolean>;
}

/**
 * Raw SQL queries used by the DAO – these are the exact strings the
 * AST analyser will scan for `users` table references.
 *
 * Each query is a `CodeReference` candidate with kind: "raw_sql_query".
 */
export const USER_QUERIES = {
  FIND_BY_ID: "SELECT * FROM users WHERE id = $1",
  FIND_BY_EMAIL: "SELECT * FROM users WHERE email = $1",
  INSERT: `
    INSERT INTO users (email, password_hash, display_name, avatar_url, bio)
    VALUES ($1, $2, $3, $4, $5)
    RETURNING *
  `,
  UPDATE: "UPDATE users SET updated_at = NOW() WHERE id = $1 RETURNING *",
  DELETE: "DELETE FROM users WHERE id = $1",
} as const;

// Placeholder stub – real implementation requires a DB connection pool.
// export class UserDAO implements IUserDAO { ... }  // TODO: not yet implemented
