/**
 * examples/users-split/services/user-service.ts
 *
 * Service fixture for user-related business logic (pre-migration).
 * Demonstrates the service layer that SchemaForge's AST analyser will
 * detect as depending on the monolithic `users` table via the DAO.
 *
 * Status: FIXTURE ONLY – interfaces and types only, no implementation.
 * The refactored service will be generated by the Code Refactor stage.
 */

import type { User } from "../models/user";
import type { IUserDAO } from "../dao/user-dao";

// ---------------------------------------------------------------------------
// DTOs used by the service
// ---------------------------------------------------------------------------

export interface CreateUserDTO {
  email: string;
  password: string; // plain-text – hashing is the service's responsibility
  displayName?: string;
}

export interface UpdateUserDTO {
  displayName?: string;
  avatarUrl?: string;
  bio?: string;
}

// ---------------------------------------------------------------------------
// Service interface
// ---------------------------------------------------------------------------

/**
 * IUserService – will be split into IAuthService + IProfileService
 * after the migration.
 *
 * ⚠️  NOT YET IMPLEMENTED – pending DB connection and password hashing.
 */
export interface IUserService {
  getUser(id: string): Promise<User | null>;
  getUserByEmail(email: string): Promise<User | null>;
  createUser(dto: CreateUserDTO): Promise<User>;
  updateUser(id: string, dto: UpdateUserDTO): Promise<User | null>;
  deleteUser(id: string): Promise<boolean>;
}

// Placeholder stub – real implementation requires dao + crypto dependencies.
// export class UserService implements IUserService {
//   constructor(private readonly dao: IUserDAO) {}
//   ...
// }  // TODO: not yet implemented

// Suppress unused-import warning until implementation is wired in.
type _IUserDAO = IUserDAO;
